project_id = "sqmzffsddfdjdczyoqbh"

[functions.analyze-brand]
verify_jwt = false

[functions.generate-fibo]
verify_jwt = false

[functions.analyze-product-image]
verify_jwt = false

[functions.generate-product-shot]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.check-video-status]
verify_jwt = false

[functions.generate-post]
verify_jwt = false
